[package]
name = "simpleaf"
version = "0.4.0"
edition = "2021"
authors = [
  "Rob Patro <rob@cs.umd.edu>",
  "Dongze He <dhe17@umd.edu>",
]
description = "A rust framework to make using alevin-fry even simpler."
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/COMBINE-lab/simpleaf"
homepage = "https://github.com/COMBINE-lab/simpleaf"
#documentation = "https://alevin-fry.readthedocs.io/en/latest/"
include = [
  "/src/*.rs",
  "/src/utils/*.rs",
  "/Cargo.toml",
  "/Cargo.lock",
  "/README.md",
  "/LICENSE",
]
keywords = [
  "single-cell",
  "preprocessing",
  "RNA-seq",
  "single-nucleus",
  "RNA-velocity",
]
categories = ["command-line-utilities", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
clap = { version = ">=3.2.17", features = ["derive", "wrap_help", "cargo", "deprecated", "wrap_help"]} 
cmd_lib = "^1.3.0"
env_logger = "^0.9.0"
log = "^0.4.17"
semver = "^1.0.12"
serde = {version = "1.0.139", features = ["derive"]}
serde_json = "1.0.82"
time = {version = "^0.3.11", features = ["macros", "formatting", "parsing", "serde", "serde-human-readable"]}
which = "^4.2.5"


[profile.release]
lto = "thin"
opt-level = 3
