[package]
name = "simpleaf"
version = "0.13.0"
edition = "2021"
authors = [
  "Rob Patro <rob@cs.umd.edu>",
  "Dongze He <dhe17@umd.edu>",
]
description = "A rust framework to make using alevin-fry even simpler."
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/COMBINE-lab/simpleaf"
homepage = "https://github.com/COMBINE-lab/simpleaf"
#documentation = "https://alevin-fry.readthedocs.io/en/latest/"
include = [
  "/src/*.rs",
  "/src/utils/*.rs",
  "/src/simpleaf_commands/*.rs",
  "/Cargo.toml",
  "/Cargo.lock",
  "/README.md",
  "/LICENSE",
]
keywords = [
  "single-cell",
  "preprocessing",
  "RNA-seq",
  "single-nucleus",
  "RNA-velocity",
]
categories = ["command-line-utilities", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seq_geom_parser = { git = "https://github.com/COMBINE-lab/seq_geom_parser", branch = "dev", version = "0.3.0" }
seq_geom_xform = { git = "https://github.com/COMBINE-lab/seq_geom_xform", branch = "dev", version = "0.4.0" }
anyhow = "^1.0"
clap = { version = "4.2.7", features = ["derive", "cargo", "deprecated", "wrap_help", "help", "usage", "error-context"] } 
cmd_lib = "^1.3.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", default-features = true, features = ["env-filter"] }
semver = "^1.0.17"
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"
time = {version = "^0.3.21", features = ["macros", "formatting", "parsing", "serde", "serde-human-readable"]}
which = "^4.4.0"
jrsonnet-evaluator = "0.5.0-pre9"
jrsonnet-cli = "0.5.0-pre9"
jrsonnet-parser = "0.5.0-pre9"
thiserror = "1.0"
phf = { version = "0.11.1", features = ["macros"] }
chrono = "0.4.24"
tabled = "0.12.0"

[profile.release]
lto = "thin"
opt-level = 3
